services:
  - type: web
    name: insighti-backend-v2
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=$PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" && npm install --prefer-offline --no-audit --loglevel=verbose
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: insighti-super-secret-key-2024
      - key: JWT_EXPIRES_IN
        value: 3d
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
